// internal/templates/desktop/pages/home.tsx
export function Head() {
	return (
		<>
			<title>Desktop App</title>
			<meta name="description" content="Bifrost Desktop Application" />
		</>
	);
}

export function Page() {
	return (
		<div
			style={{
				padding: "2rem",
				fontFamily: "system-ui, sans-serif",
			}}
		>
			<h1>Bifrost Desktop</h1>
			<p>Your desktop app is running!</p>
		</div>
	);
}

// internal/templates/svelte/pages/home.svelte
<script lang="ts">
  let { message }: { message: string } = $props();
</script>

<svelte:head>
  <title>Welcome to Bifrost</title>
  <meta name="description" content="Bifrost app" />
</svelte:head>

<div style="padding: 2rem; font-family: system-ui, sans-serif;">
  <h1>{message}</h1>
  <p>Your Bifrost app is running!</p>
</div>
