// internal/templates/svelte/pages/home.svelte
<script lang="ts">
  import "../style.css";
  let { message }: { message: string } = $props();
</script>

<svelte:head>
  <title>Welcome to Bifrost</title>
  <meta name="description" content="Bifrost app" />
</svelte:head>

<div class="flex min-h-screen flex-col items-center justify-center gap-2">
  <h1 class="text-3xl font-bold">{message}</h1>
  <p class="text-gray-600">Your Bifrost app is running!</p>
</div>

// internal/templates/spa/pages/home.tsx
import "../style.css";

export function Head() {
	return (
		<>
			<title>SPA Example</title>
			<meta name="description" content="Bifrost SPA" />
		</>
	);
}

export function Page() {
	return (
		<div className="flex min-h-screen flex-col items-center justify-center gap-2">
			<h1 className="text-3xl font-bold">Single Page Application</h1>
			<p className="text-gray-600">This is a client-only SPA template!</p>
		</div>
	);
}
